/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDataSiswaRouteImport } from './routes/_app.data-siswa'
import { Route as AppKelolaLkpdRouteImport } from './routes/_app.kelola-lkpd'
import { Route as AppKelolaMateriRouteImport } from './routes/_app.kelola-materi'
import { Route as AppKelolaQuizRouteImport } from './routes/_app.kelola-quiz'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppNilaiRouteImport } from './routes/_app.nilai'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppPosttestRouteImport } from './routes/_app.posttest'
import { Route as AppPretestRouteImport } from './routes/_app.pretest'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppRefleksiRouteImport } from './routes/_app.refleksi'
import { Route as AppRekapNilaiRouteImport } from './routes/_app.rekap-nilai'
import { Route as AppMateriIndexRouteImport } from './routes/_app.materi.index'
import { Route as AppMateriIdRouteImport } from './routes/_app.materi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSiswaRoute = AppDataSiswaRouteImport.update({
  id: '/data-siswa',
  path: '/data-siswa',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaLkpdRoute = AppKelolaLkpdRouteImport.update({
  id: '/kelola-lkpd',
  path: '/kelola-lkpd',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaMateriRoute = AppKelolaMateriRouteImport.update({
  id: '/kelola-materi',
  path: '/kelola-materi',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaQuizRoute = AppKelolaQuizRouteImport.update({
  id: '/kelola-quiz',
  path: '/kelola-quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppNilaiRoute = AppNilaiRouteImport.update({
  id: '/nilai',
  path: '/nilai',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPosttestRoute = AppPosttestRouteImport.update({
  id: '/posttest',
  path: '/posttest',
  getParentRoute: () => AppRoute,
} as any)
const AppPretestRoute = AppPretestRouteImport.update({
  id: '/pretest',
  path: '/pretest',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppRefleksiRoute = AppRefleksiRouteImport.update({
  id: '/refleksi',
  path: '/refleksi',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapNilaiRoute = AppRekapNilaiRouteImport.update({
  id: '/rekap-nilai',
  path: '/rekap-nilai',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriIndexRoute = AppMateriIndexRouteImport.update({
  id: '/materi/',
  path: '/materi/',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriIdRoute = AppMateriIdRouteImport.update({
  id: '/materi/$id',
  path: '/materi/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-siswa': typeof AppDataSiswaRoute
  '/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/kelola-materi': typeof AppKelolaMateriRoute
  '/kelola-quiz': typeof AppKelolaQuizRoute
  '/laporan': typeof AppLaporanRoute
  '/nilai': typeof AppNilaiRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/posttest': typeof AppPosttestRoute
  '/pretest': typeof AppPretestRoute
  '/profil': typeof AppProfilRoute
  '/refleksi': typeof AppRefleksiRoute
  '/rekap-nilai': typeof AppRekapNilaiRoute
  '/materi/$id': typeof AppMateriIdRoute
  '/materi/': typeof AppMateriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-siswa': typeof AppDataSiswaRoute
  '/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/kelola-materi': typeof AppKelolaMateriRoute
  '/kelola-quiz': typeof AppKelolaQuizRoute
  '/laporan': typeof AppLaporanRoute
  '/nilai': typeof AppNilaiRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/posttest': typeof AppPosttestRoute
  '/pretest': typeof AppPretestRoute
  '/profil': typeof AppProfilRoute
  '/refleksi': typeof AppRefleksiRoute
  '/rekap-nilai': typeof AppRekapNilaiRoute
  '/materi/$id': typeof AppMateriIdRoute
  '/materi': typeof AppMateriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-siswa': typeof AppDataSiswaRoute
  '/_app/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/_app/kelola-materi': typeof AppKelolaMateriRoute
  '/_app/kelola-quiz': typeof AppKelolaQuizRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/nilai': typeof AppNilaiRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/posttest': typeof AppPosttestRoute
  '/_app/pretest': typeof AppPretestRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/refleksi': typeof AppRefleksiRoute
  '/_app/rekap-nilai': typeof AppRekapNilaiRoute
  '/_app/materi/$id': typeof AppMateriIdRoute
  '/_app/materi/': typeof AppMateriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-siswa'
    | '/kelola-lkpd'
    | '/kelola-materi'
    | '/kelola-quiz'
    | '/laporan'
    | '/nilai'
    | '/pengaturan'
    | '/posttest'
    | '/pretest'
    | '/profil'
    | '/refleksi'
    | '/rekap-nilai'
    | '/materi/$id'
    | '/materi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-siswa'
    | '/kelola-lkpd'
    | '/kelola-materi'
    | '/kelola-quiz'
    | '/laporan'
    | '/nilai'
    | '/pengaturan'
    | '/posttest'
    | '/pretest'
    | '/profil'
    | '/refleksi'
    | '/rekap-nilai'
    | '/materi/$id'
    | '/materi'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/data-siswa'
    | '/_app/kelola-lkpd'
    | '/_app/kelola-materi'
    | '/_app/kelola-quiz'
    | '/_app/laporan'
    | '/_app/nilai'
    | '/_app/pengaturan'
    | '/_app/posttest'
    | '/_app/pretest'
    | '/_app/profil'
    | '/_app/refleksi'
    | '/_app/rekap-nilai'
    | '/_app/materi/$id'
    | '/_app/materi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-siswa': {
      id: '/_app/data-siswa'
      path: '/data-siswa'
      fullPath: '/data-siswa'
      preLoaderRoute: typeof AppDataSiswaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-lkpd': {
      id: '/_app/kelola-lkpd'
      path: '/kelola-lkpd'
      fullPath: '/kelola-lkpd'
      preLoaderRoute: typeof AppKelolaLkpdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-materi': {
      id: '/_app/kelola-materi'
      path: '/kelola-materi'
      fullPath: '/kelola-materi'
      preLoaderRoute: typeof AppKelolaMateriRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-quiz': {
      id: '/_app/kelola-quiz'
      path: '/kelola-quiz'
      fullPath: '/kelola-quiz'
      preLoaderRoute: typeof AppKelolaQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nilai': {
      id: '/_app/nilai'
      path: '/nilai'
      fullPath: '/nilai'
      preLoaderRoute: typeof AppNilaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posttest': {
      id: '/_app/posttest'
      path: '/posttest'
      fullPath: '/posttest'
      preLoaderRoute: typeof AppPosttestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pretest': {
      id: '/_app/pretest'
      path: '/pretest'
      fullPath: '/pretest'
      preLoaderRoute: typeof AppPretestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refleksi': {
      id: '/_app/refleksi'
      path: '/refleksi'
      fullPath: '/refleksi'
      preLoaderRoute: typeof AppRefleksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap-nilai': {
      id: '/_app/rekap-nilai'
      path: '/rekap-nilai'
      fullPath: '/rekap-nilai'
      preLoaderRoute: typeof AppRekapNilaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materi/': {
      id: '/_app/materi/'
      path: '/materi'
      fullPath: '/materi/'
      preLoaderRoute: typeof AppMateriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materi/$id': {
      id: '/_app/materi/$id'
      path: '/materi/$id'
      fullPath: '/materi/$id'
      preLoaderRoute: typeof AppMateriIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataSiswaRoute: typeof AppDataSiswaRoute
  AppKelolaLkpdRoute: typeof AppKelolaLkpdRoute
  AppKelolaMateriRoute: typeof AppKelolaMateriRoute
  AppKelolaQuizRoute: typeof AppKelolaQuizRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppNilaiRoute: typeof AppNilaiRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPosttestRoute: typeof AppPosttestRoute
  AppPretestRoute: typeof AppPretestRoute
  AppProfilRoute: typeof AppProfilRoute
  AppRefleksiRoute: typeof AppRefleksiRoute
  AppRekapNilaiRoute: typeof AppRekapNilaiRoute
  AppMateriIdRoute: typeof AppMateriIdRoute
  AppMateriIndexRoute: typeof AppMateriIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDataSiswaRoute: AppDataSiswaRoute,
  AppKelolaLkpdRoute: AppKelolaLkpdRoute,
  AppKelolaMateriRoute: AppKelolaMateriRoute,
  AppKelolaQuizRoute: AppKelolaQuizRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppNilaiRoute: AppNilaiRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPosttestRoute: AppPosttestRoute,
  AppPretestRoute: AppPretestRoute,
  AppProfilRoute: AppProfilRoute,
  AppRefleksiRoute: AppRefleksiRoute,
  AppRekapNilaiRoute: AppRekapNilaiRoute,
  AppMateriIdRoute: AppMateriIdRoute,
  AppMateriIndexRoute: AppMateriIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
