/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDataSiswaRouteImport } from './routes/_app.data-siswa'
import { Route as AppKelolaKelompokRouteImport } from './routes/_app.kelola-kelompok'
import { Route as AppKelolaLkpdRouteImport } from './routes/_app.kelola-lkpd'
import { Route as AppKelolaPosttestSiklus1RouteImport } from './routes/_app.kelola-posttest-siklus1'
import { Route as AppKelolaPosttestSiklus2RouteImport } from './routes/_app.kelola-posttest-siklus2'
import { Route as AppKelolaPosttestSiklus3RouteImport } from './routes/_app.kelola-posttest-siklus3'
import { Route as AppKelolaPresentasiRouteImport } from './routes/_app.kelola-presentasi'
import { Route as AppKelolaPretestRouteImport } from './routes/_app.kelola-pretest'
import { Route as AppKelolaTanggapanRouteImport } from './routes/_app.kelola-tanggapan'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppNilaiRouteImport } from './routes/_app.nilai'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppPosttestSiklus1RouteImport } from './routes/_app.posttest-siklus1'
import { Route as AppPosttestSiklus2RouteImport } from './routes/_app.posttest-siklus2'
import { Route as AppPosttestSiklus3RouteImport } from './routes/_app.posttest-siklus3'
import { Route as AppPretestRouteImport } from './routes/_app.pretest'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppRefleksiRouteImport } from './routes/_app.refleksi'
import { Route as AppRefleksiSayaRouteImport } from './routes/_app.refleksi-saya'
import { Route as AppRekapNilaiRouteImport } from './routes/_app.rekap-nilai'
import { Route as AppKelolaMateriIndexRouteImport } from './routes/_app.kelola-materi.index'
import { Route as AppKelolaMateriIdRouteImport } from './routes/_app.kelola-materi.$id'
import { Route as AppMateriIndexRouteImport } from './routes/_app.materi.index'
import { Route as AppMateriIdRouteImport } from './routes/_app.materi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSiswaRoute = AppDataSiswaRouteImport.update({
  id: '/data-siswa',
  path: '/data-siswa',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaKelompokRoute = AppKelolaKelompokRouteImport.update({
  id: '/kelola-kelompok',
  path: '/kelola-kelompok',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaLkpdRoute = AppKelolaLkpdRouteImport.update({
  id: '/kelola-lkpd',
  path: '/kelola-lkpd',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaPosttestSiklus1Route =
  AppKelolaPosttestSiklus1RouteImport.update({
    id: '/kelola-posttest-siklus1',
    path: '/kelola-posttest-siklus1',
    getParentRoute: () => AppRoute,
  } as any)
const AppKelolaPosttestSiklus2Route =
  AppKelolaPosttestSiklus2RouteImport.update({
    id: '/kelola-posttest-siklus2',
    path: '/kelola-posttest-siklus2',
    getParentRoute: () => AppRoute,
  } as any)
const AppKelolaPosttestSiklus3Route =
  AppKelolaPosttestSiklus3RouteImport.update({
    id: '/kelola-posttest-siklus3',
    path: '/kelola-posttest-siklus3',
    getParentRoute: () => AppRoute,
  } as any)
const AppKelolaPresentasiRoute = AppKelolaPresentasiRouteImport.update({
  id: '/kelola-presentasi',
  path: '/kelola-presentasi',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaPretestRoute = AppKelolaPretestRouteImport.update({
  id: '/kelola-pretest',
  path: '/kelola-pretest',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaTanggapanRoute = AppKelolaTanggapanRouteImport.update({
  id: '/kelola-tanggapan',
  path: '/kelola-tanggapan',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppNilaiRoute = AppNilaiRouteImport.update({
  id: '/nilai',
  path: '/nilai',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPosttestSiklus1Route = AppPosttestSiklus1RouteImport.update({
  id: '/posttest-siklus1',
  path: '/posttest-siklus1',
  getParentRoute: () => AppRoute,
} as any)
const AppPosttestSiklus2Route = AppPosttestSiklus2RouteImport.update({
  id: '/posttest-siklus2',
  path: '/posttest-siklus2',
  getParentRoute: () => AppRoute,
} as any)
const AppPosttestSiklus3Route = AppPosttestSiklus3RouteImport.update({
  id: '/posttest-siklus3',
  path: '/posttest-siklus3',
  getParentRoute: () => AppRoute,
} as any)
const AppPretestRoute = AppPretestRouteImport.update({
  id: '/pretest',
  path: '/pretest',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppRefleksiRoute = AppRefleksiRouteImport.update({
  id: '/refleksi',
  path: '/refleksi',
  getParentRoute: () => AppRoute,
} as any)
const AppRefleksiSayaRoute = AppRefleksiSayaRouteImport.update({
  id: '/refleksi-saya',
  path: '/refleksi-saya',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapNilaiRoute = AppRekapNilaiRouteImport.update({
  id: '/rekap-nilai',
  path: '/rekap-nilai',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaMateriIndexRoute = AppKelolaMateriIndexRouteImport.update({
  id: '/kelola-materi/',
  path: '/kelola-materi/',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaMateriIdRoute = AppKelolaMateriIdRouteImport.update({
  id: '/kelola-materi/$id',
  path: '/kelola-materi/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriIndexRoute = AppMateriIndexRouteImport.update({
  id: '/materi/',
  path: '/materi/',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriIdRoute = AppMateriIdRouteImport.update({
  id: '/materi/$id',
  path: '/materi/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-siswa': typeof AppDataSiswaRoute
  '/kelola-kelompok': typeof AppKelolaKelompokRoute
  '/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/kelola-posttest-siklus1': typeof AppKelolaPosttestSiklus1Route
  '/kelola-posttest-siklus2': typeof AppKelolaPosttestSiklus2Route
  '/kelola-posttest-siklus3': typeof AppKelolaPosttestSiklus3Route
  '/kelola-presentasi': typeof AppKelolaPresentasiRoute
  '/kelola-pretest': typeof AppKelolaPretestRoute
  '/kelola-tanggapan': typeof AppKelolaTanggapanRoute
  '/laporan': typeof AppLaporanRoute
  '/nilai': typeof AppNilaiRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/posttest-siklus1': typeof AppPosttestSiklus1Route
  '/posttest-siklus2': typeof AppPosttestSiklus2Route
  '/posttest-siklus3': typeof AppPosttestSiklus3Route
  '/pretest': typeof AppPretestRoute
  '/profil': typeof AppProfilRoute
  '/refleksi': typeof AppRefleksiRoute
  '/refleksi-saya': typeof AppRefleksiSayaRoute
  '/rekap-nilai': typeof AppRekapNilaiRoute
  '/kelola-materi/$id': typeof AppKelolaMateriIdRoute
  '/materi/$id': typeof AppMateriIdRoute
  '/kelola-materi/': typeof AppKelolaMateriIndexRoute
  '/materi/': typeof AppMateriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-siswa': typeof AppDataSiswaRoute
  '/kelola-kelompok': typeof AppKelolaKelompokRoute
  '/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/kelola-posttest-siklus1': typeof AppKelolaPosttestSiklus1Route
  '/kelola-posttest-siklus2': typeof AppKelolaPosttestSiklus2Route
  '/kelola-posttest-siklus3': typeof AppKelolaPosttestSiklus3Route
  '/kelola-presentasi': typeof AppKelolaPresentasiRoute
  '/kelola-pretest': typeof AppKelolaPretestRoute
  '/kelola-tanggapan': typeof AppKelolaTanggapanRoute
  '/laporan': typeof AppLaporanRoute
  '/nilai': typeof AppNilaiRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/posttest-siklus1': typeof AppPosttestSiklus1Route
  '/posttest-siklus2': typeof AppPosttestSiklus2Route
  '/posttest-siklus3': typeof AppPosttestSiklus3Route
  '/pretest': typeof AppPretestRoute
  '/profil': typeof AppProfilRoute
  '/refleksi': typeof AppRefleksiRoute
  '/refleksi-saya': typeof AppRefleksiSayaRoute
  '/rekap-nilai': typeof AppRekapNilaiRoute
  '/kelola-materi/$id': typeof AppKelolaMateriIdRoute
  '/materi/$id': typeof AppMateriIdRoute
  '/kelola-materi': typeof AppKelolaMateriIndexRoute
  '/materi': typeof AppMateriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-siswa': typeof AppDataSiswaRoute
  '/_app/kelola-kelompok': typeof AppKelolaKelompokRoute
  '/_app/kelola-lkpd': typeof AppKelolaLkpdRoute
  '/_app/kelola-posttest-siklus1': typeof AppKelolaPosttestSiklus1Route
  '/_app/kelola-posttest-siklus2': typeof AppKelolaPosttestSiklus2Route
  '/_app/kelola-posttest-siklus3': typeof AppKelolaPosttestSiklus3Route
  '/_app/kelola-presentasi': typeof AppKelolaPresentasiRoute
  '/_app/kelola-pretest': typeof AppKelolaPretestRoute
  '/_app/kelola-tanggapan': typeof AppKelolaTanggapanRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/nilai': typeof AppNilaiRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/posttest-siklus1': typeof AppPosttestSiklus1Route
  '/_app/posttest-siklus2': typeof AppPosttestSiklus2Route
  '/_app/posttest-siklus3': typeof AppPosttestSiklus3Route
  '/_app/pretest': typeof AppPretestRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/refleksi': typeof AppRefleksiRoute
  '/_app/refleksi-saya': typeof AppRefleksiSayaRoute
  '/_app/rekap-nilai': typeof AppRekapNilaiRoute
  '/_app/kelola-materi/$id': typeof AppKelolaMateriIdRoute
  '/_app/materi/$id': typeof AppMateriIdRoute
  '/_app/kelola-materi/': typeof AppKelolaMateriIndexRoute
  '/_app/materi/': typeof AppMateriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-siswa'
    | '/kelola-kelompok'
    | '/kelola-lkpd'
    | '/kelola-posttest-siklus1'
    | '/kelola-posttest-siklus2'
    | '/kelola-posttest-siklus3'
    | '/kelola-presentasi'
    | '/kelola-pretest'
    | '/kelola-tanggapan'
    | '/laporan'
    | '/nilai'
    | '/pengaturan'
    | '/posttest-siklus1'
    | '/posttest-siklus2'
    | '/posttest-siklus3'
    | '/pretest'
    | '/profil'
    | '/refleksi'
    | '/refleksi-saya'
    | '/rekap-nilai'
    | '/kelola-materi/$id'
    | '/materi/$id'
    | '/kelola-materi/'
    | '/materi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-siswa'
    | '/kelola-kelompok'
    | '/kelola-lkpd'
    | '/kelola-posttest-siklus1'
    | '/kelola-posttest-siklus2'
    | '/kelola-posttest-siklus3'
    | '/kelola-presentasi'
    | '/kelola-pretest'
    | '/kelola-tanggapan'
    | '/laporan'
    | '/nilai'
    | '/pengaturan'
    | '/posttest-siklus1'
    | '/posttest-siklus2'
    | '/posttest-siklus3'
    | '/pretest'
    | '/profil'
    | '/refleksi'
    | '/refleksi-saya'
    | '/rekap-nilai'
    | '/kelola-materi/$id'
    | '/materi/$id'
    | '/kelola-materi'
    | '/materi'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/data-siswa'
    | '/_app/kelola-kelompok'
    | '/_app/kelola-lkpd'
    | '/_app/kelola-posttest-siklus1'
    | '/_app/kelola-posttest-siklus2'
    | '/_app/kelola-posttest-siklus3'
    | '/_app/kelola-presentasi'
    | '/_app/kelola-pretest'
    | '/_app/kelola-tanggapan'
    | '/_app/laporan'
    | '/_app/nilai'
    | '/_app/pengaturan'
    | '/_app/posttest-siklus1'
    | '/_app/posttest-siklus2'
    | '/_app/posttest-siklus3'
    | '/_app/pretest'
    | '/_app/profil'
    | '/_app/refleksi'
    | '/_app/refleksi-saya'
    | '/_app/rekap-nilai'
    | '/_app/kelola-materi/$id'
    | '/_app/materi/$id'
    | '/_app/kelola-materi/'
    | '/_app/materi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-siswa': {
      id: '/_app/data-siswa'
      path: '/data-siswa'
      fullPath: '/data-siswa'
      preLoaderRoute: typeof AppDataSiswaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-kelompok': {
      id: '/_app/kelola-kelompok'
      path: '/kelola-kelompok'
      fullPath: '/kelola-kelompok'
      preLoaderRoute: typeof AppKelolaKelompokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-lkpd': {
      id: '/_app/kelola-lkpd'
      path: '/kelola-lkpd'
      fullPath: '/kelola-lkpd'
      preLoaderRoute: typeof AppKelolaLkpdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-posttest-siklus1': {
      id: '/_app/kelola-posttest-siklus1'
      path: '/kelola-posttest-siklus1'
      fullPath: '/kelola-posttest-siklus1'
      preLoaderRoute: typeof AppKelolaPosttestSiklus1RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-posttest-siklus2': {
      id: '/_app/kelola-posttest-siklus2'
      path: '/kelola-posttest-siklus2'
      fullPath: '/kelola-posttest-siklus2'
      preLoaderRoute: typeof AppKelolaPosttestSiklus2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-posttest-siklus3': {
      id: '/_app/kelola-posttest-siklus3'
      path: '/kelola-posttest-siklus3'
      fullPath: '/kelola-posttest-siklus3'
      preLoaderRoute: typeof AppKelolaPosttestSiklus3RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-presentasi': {
      id: '/_app/kelola-presentasi'
      path: '/kelola-presentasi'
      fullPath: '/kelola-presentasi'
      preLoaderRoute: typeof AppKelolaPresentasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-pretest': {
      id: '/_app/kelola-pretest'
      path: '/kelola-pretest'
      fullPath: '/kelola-pretest'
      preLoaderRoute: typeof AppKelolaPretestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-tanggapan': {
      id: '/_app/kelola-tanggapan'
      path: '/kelola-tanggapan'
      fullPath: '/kelola-tanggapan'
      preLoaderRoute: typeof AppKelolaTanggapanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nilai': {
      id: '/_app/nilai'
      path: '/nilai'
      fullPath: '/nilai'
      preLoaderRoute: typeof AppNilaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posttest-siklus1': {
      id: '/_app/posttest-siklus1'
      path: '/posttest-siklus1'
      fullPath: '/posttest-siklus1'
      preLoaderRoute: typeof AppPosttestSiklus1RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posttest-siklus2': {
      id: '/_app/posttest-siklus2'
      path: '/posttest-siklus2'
      fullPath: '/posttest-siklus2'
      preLoaderRoute: typeof AppPosttestSiklus2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posttest-siklus3': {
      id: '/_app/posttest-siklus3'
      path: '/posttest-siklus3'
      fullPath: '/posttest-siklus3'
      preLoaderRoute: typeof AppPosttestSiklus3RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pretest': {
      id: '/_app/pretest'
      path: '/pretest'
      fullPath: '/pretest'
      preLoaderRoute: typeof AppPretestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refleksi': {
      id: '/_app/refleksi'
      path: '/refleksi'
      fullPath: '/refleksi'
      preLoaderRoute: typeof AppRefleksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refleksi-saya': {
      id: '/_app/refleksi-saya'
      path: '/refleksi-saya'
      fullPath: '/refleksi-saya'
      preLoaderRoute: typeof AppRefleksiSayaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap-nilai': {
      id: '/_app/rekap-nilai'
      path: '/rekap-nilai'
      fullPath: '/rekap-nilai'
      preLoaderRoute: typeof AppRekapNilaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-materi/': {
      id: '/_app/kelola-materi/'
      path: '/kelola-materi'
      fullPath: '/kelola-materi/'
      preLoaderRoute: typeof AppKelolaMateriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-materi/$id': {
      id: '/_app/kelola-materi/$id'
      path: '/kelola-materi/$id'
      fullPath: '/kelola-materi/$id'
      preLoaderRoute: typeof AppKelolaMateriIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materi/': {
      id: '/_app/materi/'
      path: '/materi'
      fullPath: '/materi/'
      preLoaderRoute: typeof AppMateriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materi/$id': {
      id: '/_app/materi/$id'
      path: '/materi/$id'
      fullPath: '/materi/$id'
      preLoaderRoute: typeof AppMateriIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataSiswaRoute: typeof AppDataSiswaRoute
  AppKelolaKelompokRoute: typeof AppKelolaKelompokRoute
  AppKelolaLkpdRoute: typeof AppKelolaLkpdRoute
  AppKelolaPosttestSiklus1Route: typeof AppKelolaPosttestSiklus1Route
  AppKelolaPosttestSiklus2Route: typeof AppKelolaPosttestSiklus2Route
  AppKelolaPosttestSiklus3Route: typeof AppKelolaPosttestSiklus3Route
  AppKelolaPresentasiRoute: typeof AppKelolaPresentasiRoute
  AppKelolaPretestRoute: typeof AppKelolaPretestRoute
  AppKelolaTanggapanRoute: typeof AppKelolaTanggapanRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppNilaiRoute: typeof AppNilaiRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPosttestSiklus1Route: typeof AppPosttestSiklus1Route
  AppPosttestSiklus2Route: typeof AppPosttestSiklus2Route
  AppPosttestSiklus3Route: typeof AppPosttestSiklus3Route
  AppPretestRoute: typeof AppPretestRoute
  AppProfilRoute: typeof AppProfilRoute
  AppRefleksiRoute: typeof AppRefleksiRoute
  AppRefleksiSayaRoute: typeof AppRefleksiSayaRoute
  AppRekapNilaiRoute: typeof AppRekapNilaiRoute
  AppKelolaMateriIdRoute: typeof AppKelolaMateriIdRoute
  AppMateriIdRoute: typeof AppMateriIdRoute
  AppKelolaMateriIndexRoute: typeof AppKelolaMateriIndexRoute
  AppMateriIndexRoute: typeof AppMateriIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDataSiswaRoute: AppDataSiswaRoute,
  AppKelolaKelompokRoute: AppKelolaKelompokRoute,
  AppKelolaLkpdRoute: AppKelolaLkpdRoute,
  AppKelolaPosttestSiklus1Route: AppKelolaPosttestSiklus1Route,
  AppKelolaPosttestSiklus2Route: AppKelolaPosttestSiklus2Route,
  AppKelolaPosttestSiklus3Route: AppKelolaPosttestSiklus3Route,
  AppKelolaPresentasiRoute: AppKelolaPresentasiRoute,
  AppKelolaPretestRoute: AppKelolaPretestRoute,
  AppKelolaTanggapanRoute: AppKelolaTanggapanRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppNilaiRoute: AppNilaiRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPosttestSiklus1Route: AppPosttestSiklus1Route,
  AppPosttestSiklus2Route: AppPosttestSiklus2Route,
  AppPosttestSiklus3Route: AppPosttestSiklus3Route,
  AppPretestRoute: AppPretestRoute,
  AppProfilRoute: AppProfilRoute,
  AppRefleksiRoute: AppRefleksiRoute,
  AppRefleksiSayaRoute: AppRefleksiSayaRoute,
  AppRekapNilaiRoute: AppRekapNilaiRoute,
  AppKelolaMateriIdRoute: AppKelolaMateriIdRoute,
  AppMateriIdRoute: AppMateriIdRoute,
  AppKelolaMateriIndexRoute: AppKelolaMateriIndexRoute,
  AppMateriIndexRoute: AppMateriIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
